version: '3.8'

services:
  test-database:
    image: mysql:8.0
    container_name: fulcrum-test-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: fulcrum_test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_ROOT_PASSWORD: test_root_password
    ports:
      - "3307:3306"
    volumes:
      - test_db_data:/var/lib/mysql
    networks:
      - test_network

  redis-test:
    image: redis:alpine
    container_name: fulcrum-test-redis
    ports:
      - "6380:6379"
    networks:
      - test_network

volumes:
  test_db_data:

networks:
  test_network:
    driver: bridge
