name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # The turbo.json already defines that the pipeline 'test' depends on '^build'.
      # Therefore, 'turbo run test' (invoked by 'pnpm test') will ensure
      # that the necessary builds are executed before the tests.
      - name: Run Tests
        # The root 'test' script (pnpm test) runs 'turbo run test'.
        # Environment variables like DATABASE_URL, JWT_SECRET might be needed for API integration tests.
        # These can be configured here using GitHub secrets if they differ from build/dev values.
        # For example:
        # env:
        #   DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        #   JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}
        run: pnpm test
